"""Tests for the auto-generated docs pipeline (issue #19).

These lock the FastAPI-style invariant: documentation is a *derivative* of the
code (docstrings + type hints via ``griffe``), regenerated by
``tools/gen_docs.py``. They guard against:

* documenting something not in ``__all__`` (or missing a public name);
* non-deterministic output (would make the CI ``git diff`` check flaky);
* a stale checked-in ``llms.txt`` / ``docs/api/``.

The tests need the ``docs`` extra (``griffe``); they skip cleanly when it is
absent so the default dev install still runs the full suite.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

import zai_python_helper as z

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS = REPO_ROOT / "tools" / "gen_docs.py"

# Skip the whole module if griffe (the [docs] extra) is not installed — these
# tests are about the generator, which has no runtime fallback parser.
pytestmark = pytest.mark.skipif(
    importlib.util.find_spec("griffe") is None,
    reason="griffe not installed (pip install -e '.[docs]')",
)


@pytest.fixture(scope="module")
def gen():
    """Import ``tools/gen_docs.py`` as a module (it is not a package member)."""
    spec = importlib.util.spec_from_file_location("_gen_docs_under_test", TOOLS)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


def test_docs_cover_exactly_the_public_surface(gen):
    """The generator reads exactly ``zai_python_helper.__all__`` — no drift."""
    pkg = gen.load_package()
    names = gen.public_names(pkg)
    assert set(names) == set(z.__all__), (
        "docs generator public_names() drifted from zai_python_helper.__all__"
    )
    # Every documented name must resolve to a real object in the source tree.
    missing = [n for n in names if gen.resolve_member(pkg, n) is None]
    assert missing == [], f"unresolvable public names: {missing}"


def test_generation_is_deterministic(gen):
    """Two renders of each artifact produce byte-identical output."""
    pkg = gen.load_package()
    names = gen.public_names(pkg)
    assert gen.render_api_md(pkg, names) == gen.render_api_md(pkg, names)
    assert gen.render_llms_txt(pkg, names) == gen.render_llms_txt(pkg, names)


def test_check_passes_when_artifacts_are_in_sync(gen):
    """``--check`` exits 0 after a fresh generate (the CI gate must be green).

    This is the load-bearing test for the acceptance criterion: if it fails, the
    checked-in ``docs/`` and ``llms.txt`` are out of sync with the code and CI
    will (correctly) go red.
    """
    gen.generate()  # rebuild on disk from current code
    rc = gen.main(["--check"])
    assert rc == 0, "docs are stale relative to the code — run `make docs`"


def test_llms_txt_is_valid_format(gen):
    """``llms.txt`` follows the llmstxt.org shape: H1 title, summary, links."""
    pkg = gen.load_package()
    names = gen.public_names(pkg)
    text = gen.render_llms_txt(pkg, names)
    lines = text.splitlines()
    # First non-empty line is an H1 title.
    assert lines[0].startswith("# "), "llms.txt must start with an H1 title"
    # A blockquote summary immediately follows.
    assert any(ln.startswith("> ") for ln in lines[:5]), "missing summary blockquote"
    # The public API block is present and names every exported symbol.
    for name in names:
        assert name in text, f"public name {name!r} missing from llms.txt"


def test_api_reference_lists_every_public_name(gen):
    """The detailed reference has a heading per ``__all__`` name.

    Functions render as ``### `name()``` (with parentheses); classes/enums/
    constants as ``### `name```. Both forms are accepted per name kind.
    """
    pkg = gen.load_package()
    names = gen.public_names(pkg)
    md = gen.render_api_md(pkg, names)
    for name in names:
        obj = gen.resolve_member(pkg, name)
        # Functions get trailing ``()`` in the heading; others do not.
        import griffe

        suffix = "()" if isinstance(obj, griffe.Function) else ""
        assert f"### `{name}{suffix}`" in md, f"missing reference section for {name!r}"


def test_loading_generator_does_not_register_it_as_package():
    """Loading ``tools/gen_docs.py`` must not register it as an importable
    module — it is a script, not a package member. Belt-and-braces guard so the
    fixture stays side-effect-free for the rest of the suite."""
    assert "_gen_docs_under_test" not in sys.modules
